### ISSUE TITLE
[Crop & Soil] Add support for custom crop config and growth

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1824] opened 2024-07-16 15:51 UTC
Grooming session can determine if this should be broken down further.

- Design and implement a user interface to allow users to configure and create custom crop types.
- Decide on a design to store the properties and growth characteristics of custom crops.
- Modify the existing crop growth logic to accommodate custom crops so they can managed alongside predefined crop types.
- Write documentation and give examples of how to configure custom crops.

**Comment by ew3361zh** [comment] 2024-07-24 17:23
Grooming session:
- ask new SME when they're more fully onboarded.
- all crop configs should be provided by user - i.e. all crops should be "custom". This system should be similar to how different components in the manure module are configured. This statement is attributed to @Isgotkowitz to whom you can reach out if you have further questions.

**Comment by Isgotkowitz** [comment] 2024-11-27 18:57
Grooming session: closing this issue as duplicate of #1831

**Closed as not planned by Isgotkowitz** 2024-11-27 18:57 UTC
Labels: dev-team, Crop & Soil
