### ISSUE TITLE
Not currently tracking organic phosphorus

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#167] opened 2022-07-21 16:54 UTC
From `update_all()` (tillage_application.py): "RuFaS does not track organic phosphorous (03.19.20). When it does, WOP/SOP will be incorporated into organic pools."This issue overlaps with part of Issue #164.

**Comment by Isgotkowitz** [comment] 2023-11-20 14:25
Closing as it is duplicate of #444

**Closed as completed by Isgotkowitz** 2023-11-20 14:25 UTC
Labels: enhancement
