### ISSUE TITLE
Analyze `IM.get_data()` inquires

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1320] opened 2024-02-21 13:48 UTC
Currently, it appears to have over 300,000 calls to the `InputManager.get_data()` function for data inquires. Please analyze the situation and possibly save the data at local class/method to reduce repeated function calls to speed up the simulation.

**Comment by allisterakun** [comment] 2024-02-21 18:28
@ltp23 mentioned during the grooming session that this issue is possibly related to his animal module refactor. Mostly likely related to the Cow and LifeCycle classes.

**Comment by PooyaHekmati** [comment] 2024-03-15 15:25
While PR #1355 is an improvement to the code base, the result of the analysis which is asked in the issue is not provided anywhere. The issue is not asking for reduction in IM calls in life cycle module specifically and it is not clear why the decision was made to make that reduction and how it was enough to close this task. Please provide what is requested in the issue (analyze the situation and report the results here).

**Comment by ltp23** [comment] 2024-03-15 19:52
The high number of calls to `IM.get_data()` came from the following two places:
- `Cow` class: Each day each cow needs to retrieve about 15 input parameters from the input manager. 
- `LifeCycleManager`: Every time a new calf is born, we need to assign a breed to the calf, so we retrieve this from the input manager as well. Depending on the number of calves born, the get_data() call count can vary.

So, without storing these values somewhere, the get_data() call counts will scale linearly with the number of cows, newborn calves, and days of simulation.

With the current design of the animal module, we have all these values stored inside the `AnimalBase.config` dictionary, so we can retrieve from it directly, assuming that these values are unchanged throughout the simulation.

---
Edit 1: 

After PR #1355, the number of calls to `IM.get_data()` has dropped from several hundred thousand to around 50.

**Comment by PooyaHekmati** [comment] 2024-03-15 20:03
How did IM.get_data stats look like before and after PR 1355?

**Comment by ltp23** [comment] 2024-03-15 20:41
After PR #1355, the number of calls to `IM.get_data()` has dropped from several hundred thousand to around 50.

**Closed as completed** 2024-03-15 20:49 UTC
Labels: dev-team
