### ISSUE TITLE
Find the remaining classless methods and prescribe fix

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#220] opened 2022-11-29 16:35 UTC
This issue is being created as a tracker for functions in the model that currently don't have a class constructor/don't belong to a class to make sure this is addressed and a class is created for them or they are assigned to an existing class if applicable.

## Expected Behavior
All functions should belong to a class.

## Current Behavior
Some functions in the code base are not wrapped in any classes.

## Possible Solution
If applicable, move these functions to the utility class. Create a new class(es) as a wrapper for the functions that are not utility/helper functions.

## Steps to Reproduce
Navigate to the respecting files to see these functions.
1. RUFAS > user_prompt.py
- `user_prompt()`

2. RUFAS > routines > animal > ration > pyomo_solver.py
- `model_shell()`
- `bnds()`
- `obj_cost()`
- `NDF_constraint_1()`
- `NDF_constraint_2()`
- `create_model()`

3. RUFAS > routines > animal > ration > ration_NLP.py
- `NEl_constraint()`
- `get_ration_vals()`
- `optimize()`
- `objective()`
- `set_globals()`
- `list_reconfig()`
- `NEmact_constraint()`
- `NEgact_constraint()`
- `calcium_constraint()`
- `phosphorus_constraint()` 
- `protien_constraint()` (sic)
- `NDF_constraint_1()`
- `NDF_constraint_2()`
- `forage_NDF_constraint()`
- `fat_constraint()`
- `DMI_constraint()`
- `energy_req_limit_constraint()`

4. RUFAS > routines > animal > ration > ration_driver.py
- `optimization()` 
- `ration_formulation()` 
- `calc_requirements()`

5. RUFAS > routines > animal > ration > calf_ration.py
- `get_ration()`
- `optimize()`
- `calc_requirements()`

6. RUFAS > routines > manure > dry_cow_manure_excretion.py
- `manure_calculations()`

7. RUFAS > routines > manure > growing_heifer_manure_excretion.py
- `manure_calculations()`

8. RUFAS > routines > manure > lactating_cow_manure_excretion.py
- `manure_calculations()`

9. RUFAS > routines > field > crop > crop.py
- `daily_crop_routine()`
- `daily_reset()`
- `annual_variable_update()` 
- `annual_crop_routine()` 
- `dormancy_routine()` 
- `is_kill_year()` 

10. RUFAS > routines > field > crop > yields.py
- `update_all()`
- `calc_HI_max()`
- `calc_HI_act()`
- `calc_dry_down()`
- `calc_yield_max()`
- `calc_yield_act()`
- `calc_quality_assessment()`
- `calc_nutrient_removal()`
- `calc_residue()`
- `calc_harvest_quality()`
- `kill()`
- `cut()`

11. RUFAS > routines > field > soil > soil.py
- `daily_soil_routine()`
- `daily_soil_reset()`
- `annual_variable_update()`

12. RUFAS > routines > manure_storage > manure_storage.py
- `daily_manure_storage_routine()`

13. RUFAS > routines > field > field.py
- `daily_fields_routine()`
- `annual_fields_routine()`

14. RUFAS > routines > animal > clustering_pen_grouping.py
- no functions in this module are organized into classes

## Context (Environment)
1. In OOP all functions must belong to a class.
2. OutputManager requires the class name, without a class, it is not possible to use OutputManager.

**Comment by ew3361zh** [comment] 2022-11-30 15:23
@PooyaHekmati please let me know if this is helpful in its current format going forward as a repo for modules/functions without classes

**Comment by PooyaHekmati** [comment] 2022-11-30 15:41
> @PooyaHekmati please let me know if this is helpful in its current format going forward as a repo for modules/functions without classes

Thanks for creating this. Let's use the templates that we already have. In the case of this issue, something like this would work:


## Expected Behavior

All functions should belong to a class.

## Current Behavior

Some functions in the code base are not wrapped in any classes.

## Possible Solution

If applicable, move these functions to the utility class. Create a new class(es) as a wrapper for the functions that are not utility/helper functions.

## Steps to Reproduce


Navigate to the respecting files to see these functions. 
Put the list of files here.

## Context (Environment)


1. In OOP all functions must belong to a class.
2. OutputManager requires the class name, without a class, it is not possible to use OutputManager.

## Detailed Description

Feel this in as necessary.
## Possible Implementation

Feel this in as necessary.

**Comment by PooyaHekmati** [comment] 2022-11-30 15:42
Also, please use labels.

**Comment by Ed731551** [comment] 2023-02-06 20:17
Happy to help. I would appreciate some guidelines to get more clear about my specific contribution on this. Thanks.

**Comment by morrowcj** [comment] 2023-02-07 06:53
Note that all the files in `RUFAS/routines/field/` referenced by the main issue comment are/will be addressed by #223 and the various sub-PRs associated with the `SC_redesign` branch. They should stay on this list, but I wanted to document here that the progress is being made.

**Comment by ew3361zh** [comment] 2023-02-07 14:29
Thanks, Clay - great idea adding this to a project. I was wondering what would be a good way to track the different elements across modules that fix the listed functions here.

**Comment by morrowcj** [comment] 2023-02-07 22:53
I think we should leave this main issue as is and use sub-issues to track on the per-project basis. What do others think? @JoeWaddell, @PooyaHekmati, @ew3361zh?

**Comment by ew3361zh** [comment] 2023-02-08 18:52
> I think we should leave this main issue as is and use sub-issues to track on the per-project basis. What do others think? @JoeWaddell, @PooyaHekmati, @ew3361zh?

Just to clarify @morrowcj, do you mean you want to migrate the module-specific functions to separate issues, remove those functions from this issue, and then leave this issue open for any functions that don't belong to one of those modules?

**Comment by morrowcj** [comment] 2023-02-08 19:10
No, I actually meant keep this as a master list but leave it un-tracked on our Projects. But we'd create new issues for the animal module items and the crop and soil items. We'd link those issues to this issue. 

Maybe that's overly complicated and unnecessary?

**Comment by JoeWaddell** [comment] 2023-02-08 19:13
@morrowcj To me that sounds good: as we start work on a given file (or files), we can make new issues and PRs associated with those smaller subsets of this big list. Bite-sized chunks, depending on what specific functions we're trying to refactor.

**Comment by ew3361zh** [comment] 2023-02-08 19:19
How do we eventually close this issue out? Or is this issue getting updated when the sub-issues get resolved within their projects?

**Comment by JoeWaddell** [comment] 2023-02-08 19:31
The workflow I imagine: when I start refactoring the ration module, once I'm decided on which functions I'm turning into class methods, I'll comment on those here, while making a new issue to touch on just those specific functions (since in many instances we might only refactor a few at a time, to keep PRs small). 

That said, it does sound complicated when I type all that out...so I'm open to suggestion. Maybe we just need to make an issue per file?

**Comment by ew3361zh** [comment] 2023-02-08 20:38
I think that sounds mostly okay to me but I'm curious what the advantages are of keeping those functions listed in this issue. Or would you remove them from this issue once they were incorporated into classes within a particular project?

It seems to me like extra work to keep this issue actively updated with the progress being made in projects. But maybe I'm missing the advantages of keeping the full list documented here.

**Comment by morrowcj** [comment] 2023-02-08 21:32
> It seems to me like extra work to keep this issue actively updated with the progress being made in projects. But maybe I'm missing the advantages of keeping the full list documented here.

Maybe we should just turn each point into its own issue and delete this issue? That seems like a lot of issues though.

**Comment by ew3361zh** [comment] 2023-02-08 23:06
I think I'd recommend one of the following:

1. Create a new issue for each module and move ALL the classless functions that are associated with that module into that issue and delete them from this issue. In any refactor project for that module, the new module-specific issue gets associated with it and the person in charge of the project would, at the conclusion of the refactor, remove those functions that are now associated with a class from that module issue, until that issue is totally resolved (i.e. all functions have a class for that module). 

They (or anyone) could also add new functions associated with that particular module to that issue. Module-specific classless functions would not get added here.

I like this because it gives a nice repository by module for module leaders to reference when looking for functions that need to be addressed.

OR

2. When a refactor project for a module is starting, the project owner checks this issue for classless functions that could/will be specifically addressed during the refactor and creates a new issue just for those functions. In this case the issue would be created and resolved with the project. When they created that new issue at the start of the project, they would remove the classless functions from this issue. 

I like this option because it makes the issues more specific to the projects to help show what the project addressed rather than the first option which doesn't necessarily close out the issue when the project is complete.

Either way, I think this could serve as an ongoing single repository for functions in the model that don't belong to a particular module.

**Comment by morrowcj** [comment] 2023-02-09 05:22
Thanks for laying your thoughts out, @ew3361zh. OK, I agree with you that either of these options would be good. My vote is for option 2, I think.

I'm removing our Project link from this issue now.

**Comment by JoeWaddell** [comment] 2023-09-26 14:06
All methods in pyomo_solver.py (removed), ration_NLP.py, and ration_driver.py now have classes following #743. Dealing with the two functions in calf ration is on the schedule for subsequent steps in the Ration refactor.

**Comment by Isgotkowitz** [comment] 2024-07-10 18:07
Grooming sessions: this list of classless functions is stale, reevaluate the codebase to find the remaining classless functions and list them so that they can be addressed.

**Comment by matthew7838** [comment] 2024-07-31 11:14
New issue #1876 was created with the latest updates in the current code-base.

**Closed as completed by matthew7838** 2024-07-31 11:14 UTC
Labels: enhancement, invalid, dev-team
