### ISSUE TITLE
Animals in Pen only updated with ration formulation interval

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#189] opened 2022-08-25 00:50 UTC
## Expected Behavior

animals should change pens daily if their biological state changes (i.e. their animal class changes or they change from not milking to milking). 
## Current Behavior

Currently, animals are only added or removed from pens on a daily basis if they are purchased or born using the daily_update_id_pen() function in animal_management.py. 

Animals that change classes or start or stop milking are only moved to a new pen when pen_allocation() is called at the end of a ration formulation interval (also in animal_management.py)

## Possible Solution

both daily_update_id_pen and pen_allocation probably need to be refactored/started from scratch but other than that I don't have any good suggestions. 

## Steps to Reproduce

1. Run any simulation with animals and set the ration formulation interval to something above 1 (a larger number will make the issue more apparent)
2.
3.
4.

## Context (Environment)

Tracking the animals in the pen is an essential part of the animal module. Not having the correct number of animals in the pen messes up all other pen related estimates like this enteric methane estimate I was looking at: 
![image](https://user-images.githubusercontent.com/41019131/186549178-f0dafefc-ee24-41fa-a20a-8d690c2bc582.png)

## Detailed Description

You can see this behavior in the following plot of the different pens. Pens 3 & 4 are lactating cow pens. Pen 0 is the calf pen that is only having animals added to it through birth on a daily basis but they are only 'graduating' to Pen1, the growing pen, once every 30 day ration interval. Similarly, Pen 2 is the Close-up pen which has newly purchased animals added to the herd on a daily basis but only updates to have the animals leave that pen and move to the lactating cow pens on the 30 day ration interval. 
![image](https://user-images.githubusercontent.com/41019131/186547478-0832c308-e796-4e74-b32d-ad96f56d158c.png)
The challenge with adding an animal to a pen on a day when it is not a ration formulation interval, is that we will need to update the animal attributes related to the ration so it has the same ration information as all the other animals in that pen. 

## Possible Implementation

I think we need to track which animals are changing classes and which animals are moving from milking to non milking and back again and include those animals in the daily_pen_id_update. I also don't se a reason why we need both the pen_allocation and the daily_pen_id_update. They do very similar things.

**Comment by JoeWaddell** [comment] 2023-02-02 20:03
Working on a review of PR #322 by @ltp23 , and there is significant progress regarding this bug.

These are screen clippings from the graphics as printed by RuFaS, and the data appear to match what is saved in the pen report CSVs. ![image](https://user-images.githubusercontent.com/109082924/216432275-78622959-de18-4abd-a289-fcbebe601de9.png)

I'm still early in the review, but it seems like it must have to do with the refactored methods called by daily_update for culling or growth to subsequent animal type. 
For example, `_evaluate_heiferIIs_for_transitioning_to_heiferIIIs` uses the `Utility.remove_items_from_list_by_indices` method to remove those animals at that step. The previous logic was also deleting animal objects from an array, so I haven't figured out why the previous behavior was so different, but given that I also just double-checked that we are still getting the spiky and blocky graphs on master, it seems like the logic that Loi has cleaned up is doing the trick!

Merging of said PR might close this issue, but it will require a full review to ensure that it's working as intended (e.g. I will also look at pen history for individuals to see if we're seeing the behavior reported in another issue, re: moving between pens frequently).

**Comment by KFosterReed** [comment] 2023-02-02 20:11
This sounds like exciting progress!

**Comment by Fjordrunner** [comment] 2023-02-06 05:23
The original behavior seen in Pen0 and Pen2's graphs is characterized by consistent growth followed by an immediate drop in the number of animals in the pen after a set period of time. The sharp dropoffs seems to be happening at set interval lengths, which after some more investigation appear to be the ration intervals of a given RuFaS simulation run. It should be noted that pen0 houses Calves and pen2 houses Close-Up cows, which might indicate which animal types the model is not handling correctly. The class variable `animals_in_pen` within all Pen objects is supposed to be a list of all the Animal objects currently in that pen. However, while that variable gets appended to in two separate functions within the code, it is never removed from, which is not functionally correct as cows might move from one pen to another, get sold, die, etc. The only time that the `animals_in_pen` list gets edited is when it gets reset at the end of each ration interval, which is seen in the graphs produced by the pre-PR #322 as sudden decreases towards zero. While the PR in question might handle the case somewhat, ensuring the animals are being shuffled correctly is instrumental to accurate pen reports.

**Comment by KFosterReed** [comment] 2023-02-09 15:50
So after an initial scan of PR #322 ,  I am certain this is a HUGE improvement to the lifecycle.py code and logic, I don't think it has actually addressed the pen behavior in this issue. I think the perceived improvement was mostly due to a difference in time scales... Here is the calf pen (pen 0) for just 1 year: 
![image](https://user-images.githubusercontent.com/41019131/217864083-dec9b3ee-aee3-41ac-a344-ecb75399ab45.png)

and the lactating cow pen for just one year (pen 3): 
![image](https://user-images.githubusercontent.com/41019131/217864207-e20947d1-f151-40b8-84f7-b22ad1b449bd.png)

I do still think we are close to a solution and that this refactor will make it infinitely easier to fix for real!

**Comment by JoeWaddell** [comment] 2023-02-09 16:27
My mistake! Embarrassing that I didn't catch that the simulations were set up for different time scales, but I'm glad Simon's nice detective work hasn't gone to waste. Thanks for the update on this Kristan. Next time I'll be more cautious about posting an update prior to checking it via fine-toothed comb.

**Comment by Fjordrunner** [comment] 2023-02-09 19:38
Yeah, these results make sense since the pen report outputs are almost entirely based on the Pen class variable `animals_in_pen`. After some discussion with Loi, as well as reviewing his PR's code, it would seem that he didn't make any change to that `animals_in_pen` list, meaning that we shouldn't have seen different graph behavior. I think the fix still lies in removing from that Pen class list when we are supposed to.

**Closed as completed** 2023-05-27 22:59 UTC
Labels: bug
